skip_commits:
  files:
    - ./**/*.md
    - ./**/*.yml
    - ./**/*.ps1

branches:
  only:
    - master
    
before_build:
  - nuget restore
platform: Any CPU
configuration: Release

version: '1.0.{build}'
assembly_info:
  patch: true
  file: AssemblyInfo.fs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

after_test:
  - ps: .\nuget\pack.ps1
  
artifacts:
  - path: NuSoft.FSharp.IEC.DataTypes\bin\Release\NuSoft.FSharp.IEC.DataTypes.dll
    name: NuSoft.FSharp.IEC.DataTypes.dll
  - path: '**\NuSoft.FSharp.IEC.DataTypes.*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: N3xcz9MEulgMmoxxgr/JF15rkxlRNkZ01zMQa9QwZu9BPsbdD2FbXkjc6txsi+HW
  artifact: /.*\.nupkg/
