// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("NuSoft.FSharp.IEC.DataTypes")>]
[<assembly: AssemblyProductAttribute("NuSoft.FSharp.IEC.DataTypes")>]
[<assembly: AssemblyDescriptionAttribute("IEC-61131-3 type aliases for F#")>]
[<assembly: AssemblyVersionAttribute("1.0.11")>]
[<assembly: AssemblyFileVersionAttribute("1.0.11")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "NuSoft.FSharp.IEC.DataTypes"
    let [<Literal>] AssemblyProduct = "NuSoft.FSharp.IEC.DataTypes"
    let [<Literal>] AssemblyDescription = "IEC-61131-3 type aliases for F#"
    let [<Literal>] AssemblyVersion = "1.0.11"
    let [<Literal>] AssemblyFileVersion = "1.0.11"
    let [<Literal>] AssemblyConfiguration = "Release"
